on: pull_request_target

jobs:
  Comment_on_PR:
    runs-on: ubuntu-latest
    name: Leave a comment on the Pull Request
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            Thank you for your pull request!  Staff will review your submission, and if it passes all checks, it will be merged. After merging, you may check the merged file. :wave:

